const skills = [
  {
    skillId: 1,
    skillName: "Beginner Guitar Lessons",
    providerName: "Alex Martin",
    providerEmail: "alex@skillswap.com",
    price: 20,
    rating: 4.8,
    slotsAvailable: 3,
    description: "Acoustic guitar classes for complete beginners.",
    image:
      "https://furtadosschoolofmusic.com/wp-content/uploads/2024/11/guitar-lessons-1568x896.jpg",
    category: "Music",
  },
  {
    skillId: 2,
    skillName: "Spoken English Practice",
    providerName: "Sara Hossain",
    providerEmail: "sara@skillswap.com",
    price: 10,
    rating: 4.6,
    slotsAvailable: 5,
    description: "Conversational English sessions for non-native speakers.",
    image:
      "https://eduurban.com/wp-content/uploads/2022/09/Rev_Web_Banner_Edu_Urban_a_Spoken_English_Main_Banner.jpg",
    category: "Language",
  },
  {
    skillId: 3,
    skillName: "Basic Web Development",
    providerName: "John Carter",
    providerEmail: "john@skillswap.com",
    price: 25,
    rating: 4.9,
    slotsAvailable: 4,
    description: "Learn HTML, CSS, and JavaScript to build your first website.",
    image: "https://miro.medium.com/1*V-Jp13LvtVc2IiY2fp4qYw.jpeg",
    category: "Technology",
  },
  {
    skillId: 4,
    skillName: "Photography Essentials",
    providerName: "Emma Rodriguez",
    providerEmail: "emma@skillswap.com",
    price: 18,
    rating: 4.7,
    slotsAvailable: 2,
    description:
      "Master camera settings, composition, and lighting techniques.",
    image: "https://static-cse.canva.com/blob/1145468/Photography_Canva28.jpg",
    category: "Photography",
  },
  {
    skillId: 5,
    skillName: "Yoga for Beginners",
    providerName: "Lina Das",
    providerEmail: "lina@skillswap.com",
    price: 12,
    rating: 4.5,
    slotsAvailable: 6,
    description: "Gentle yoga sessions to improve flexibility and relaxation.",
    image:
      "https://articles-1mg.gumlet.io/articles/wp-content/uploads/2015/09/yoga3-2.jpg?w=300&compress=true&quality=80&dpr=2.6",
    category: "Health & Fitness",
  },
  {
    skillId: 6,
    skillName: "Creative Writing Workshop",
    providerName: "Noah Patel",
    providerEmail: "noah@skillswap.com",
    price: 15,
    rating: 4.8,
    slotsAvailable: 3,
    description:
      "Enhance your storytelling skills and explore your imagination.",
    image: "https://media.zaner-bloser.com/images/photos/pg-1-welcome.png",
    category: "Writing",
  },
  {
    skillId: 7,
    skillName: "Cooking Indian Cuisine",
    providerName: "Priya Mehta",
    providerEmail: "priya@skillswap.com",
    price: 22,
    rating: 4.9,
    slotsAvailable: 4,
    description: "Learn authentic Indian recipes and cooking techniques.",
    image:
      "https://www.eatright.org/-/media/images/eatright-articles/eatright-main-featured---804x482px/learntocookathome_804x482.jpg?h=482&w=804&rev=ba2d868e41744f6c93dd5ed8c20a1361&hash=A83B129B92BD360E2027A006AA2FAD1B",
    category: "Cooking",
  },
  {
    skillId: 8,
    skillName: "Digital Marketing Basics",
    providerName: "David Kim",
    providerEmail: "david@skillswap.com",
    price: 30,
    rating: 4.7,
    slotsAvailable: 5,
    description:
      "Understand SEO, social media, and online advertising strategies.",
    image:
      "https://www.springboard.com/blog/wp-content/uploads/2022/06/what-is-digital-marketing.png",
    category: "Business",
  },
];
export default skills; 